// GENERATED by scripts/scaffold-routes.mjs — DO NOT EDIT.
// Re-export de corps de page vivant dans un package @ef/*. Modifier le
// package, pas ce fichier. Regénéré par predev/prebuild (scaffold).

export { default } from '@ef/partner-events/pages/event-create-page';
