#!/usr/bin/env node
// scaffold-routes.mjs — codegen des routes d'une app depuis ses modules.
//
// Usage: node scripts/scaffold-routes.mjs apps/<app>
//
// Lit apps/<app>/modules.json, puis chaque packages/<id>/routes.manifest.json,
// et écrit l'arbre app/<basePath>/<route> comme de simples re-exports (P9/P10).
// - Idempotent : chaque fichier généré porte une bannière GENERATED.
// - Pruning : les fichiers générés obsolètes (bannière présente, plus au manifeste)
//   sont supprimés.
// - cwd-agnostique : anchré sur sa propre position (import.meta.url), pas sur cwd.

import { fileURLToPath } from 'node:url';
import path from 'node:path';
import fs from 'node:fs';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
// scripts/ est à la racine du monorepo → la racine est le parent de __dirname.
const REPO_ROOT = path.resolve(__dirname, '..');

const BANNER =
  '// GENERATED by scripts/scaffold-routes.mjs — DO NOT EDIT.\n' +
  '// Re-export de corps de page vivant dans un package @ef/*. Modifier le\n' +
  '// package, pas ce fichier. Regénéré par predev/prebuild (scaffold).\n';

const BANNER_MARK = 'GENERATED by scripts/scaffold-routes.mjs';

function fail(msg) {
  console.error(`[scaffold] ERREUR: ${msg}`);
  process.exit(1);
}

// --- Args ---------------------------------------------------------------
const appArg = process.argv[2];
if (!appArg) fail('argument manquant. Usage: node scripts/scaffold-routes.mjs apps/<app>');

const appDir = path.resolve(REPO_ROOT, appArg);
if (!fs.existsSync(appDir)) fail(`app introuvable: ${appArg}`);

const modulesJsonPath = path.join(appDir, 'modules.json');
if (!fs.existsSync(modulesJsonPath)) fail(`modules.json introuvable dans ${appArg}`);

const { modules } = JSON.parse(fs.readFileSync(modulesJsonPath, 'utf8'));
if (!Array.isArray(modules)) fail('modules.json: champ "modules" absent ou invalide');

const appName = path.basename(appDir);
const packagesDir = path.join(REPO_ROOT, 'packages');

// --- Résolution : nom de package @ef/<id> → dossier packages/<id> --------
function packageDirFor(pkgName) {
  // Convention : @ef/<id> vit dans packages/<id>.
  const id = pkgName.replace(/^@ef\//, '');
  const dir = path.join(packagesDir, id);
  return { id, dir };
}

// --- Collecte des routes voulues depuis les manifestes -------------------
const desired = []; // { absFile, contents }
for (const pkgName of modules) {
  const { id, dir } = packageDirFor(pkgName);
  const manifestPath = path.join(dir, 'routes.manifest.json');
  if (!fs.existsSync(manifestPath)) {
    fail(`routes.manifest.json introuvable pour ${pkgName} (attendu: ${path.relative(REPO_ROOT, manifestPath)})`);
  }
  const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
  const basePath = manifest.basePath || '';
  const pkg = manifest.package || pkgName;

  for (const r of manifest.routes || []) {
    // r.route  : chemin sous basePath, ex. "sandbox/page.tsx"
    // r.module : fichier dans <package>/pages/, ex. "sandbox-page"
    // r.export : export nommé re-exporté en default (optionnel)
    const routeRel = r.route;
    const importPath = `${pkg}/pages/${r.module}`;
    const absFile = path.join(appDir, 'app', basePath, routeRel);

    let body;
    if (r.export && r.export !== 'default') {
      body =
        `export { ${r.export} as default } from '${importPath}';\n`;
    } else {
      body = `export { default } from '${importPath}';\n`;
    }
    desired.push({ absFile, contents: BANNER + '\n' + body });
  }
}

// --- Écriture (idempotente) ---------------------------------------------
const desiredSet = new Set(desired.map((d) => path.resolve(d.absFile)));
let written = 0;
for (const { absFile, contents } of desired) {
  fs.mkdirSync(path.dirname(absFile), { recursive: true });
  const existing = fs.existsSync(absFile) ? fs.readFileSync(absFile, 'utf8') : null;
  if (existing !== contents) {
    if (existing !== null && !existing.includes(BANNER_MARK)) {
      fail(`refus d'écraser un fichier NON généré: ${path.relative(REPO_ROOT, absFile)}`);
    }
    fs.writeFileSync(absFile, contents);
    written++;
  }
}

// --- Pruning : supprimer les fichiers générés obsolètes ------------------
let pruned = 0;
const appAppDir = path.join(appDir, 'app');
function walk(dir) {
  if (!fs.existsSync(dir)) return;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      walk(full);
      // supprimer les dossiers devenus vides
      if (fs.existsSync(full) && fs.readdirSync(full).length === 0) {
        fs.rmdirSync(full);
      }
    } else if (entry.isFile()) {
      if (desiredSet.has(path.resolve(full))) continue;
      const txt = fs.readFileSync(full, 'utf8');
      if (txt.includes(BANNER_MARK)) {
        fs.unlinkSync(full);
        pruned++;
      }
    }
  }
}
walk(appAppDir);

console.log(
  `[scaffold] ${appName}: ${desired.length} route(s), ${written} écrite(s), ${pruned} obsolète(s) supprimée(s).`,
);
